<?php

class utils_constant {

    CONST SUCCESS = '100';
    CONST SUCCESSWITHMESSAGE = '101';
    CONST CREATED = '201';             //	THE REQUEST HAS BEEN FULFILLED, AND A NEW RESOURCE IS CREATED 
    CONST ACCEPTED = '202';            //	THE REQUEST HAS BEEN ACCEPTED FOR PROCESSING, BUT THE PROCESSING HAS NOT BEEN COMPLETED
    CONST ERROR_NO_CONTENT = '204';          //       THE REQUEST HAS BEEN SUCCESSFULLY PROCESSED, BUT IS NOT RETURNING ANY CONTENT              
    CONST ERROR_BAD_REQUEST = '400';         //       THE REQUEST CANNOT BE FULFILLED DUE TO BAD SYNTAX    
    CONST ERROR_UNAUTHORIZED = '401';        //       THE REQUEST WAS A LEGAL REQUEST, BUT THE SERVER IS REFUSING TO RESPOND TO IT. FOR USE WHEN AUTHENTICATION IS POSSIBLE BUT HAS FAILED OR NOT YET BEEN PROVIDED 
    CONST ERROR_PAYMENT_REQUIRED = '402';     //       RESERVED FOR FUTURE USE NOT PAID
    CONST ERROR_FORBIDDEN = '403';            //       THE REQUEST WAS A LEGAL REQUEST, BUT THE SERVER IS REFUSING TO RESPOND TO IT 
    CONST ERROR_NOT_FOUND = '404';
    CONST ERROR_CONFLICT = '409';              //       THE REQUEST COULD NOT BE COMPLETED BECAUSE OF A CONFLICT IN THE REQUEST
    CONST ERROR_UNSUPPORTEDMEDIATYPE = '415'; //       THE SERVER WILL NOT ACCEPT THE REQUEST, BECAUSE THE MEDIA TYPE IS NOT SUPPORTED 
    CONST ERROR_INTERNAL_SERVER_ERROR = '500'; //       A GENERIC ERROR MESSAGE, GIVEN WHEN NO MORE SPECIFIC MESSAGE IS SUITABLE
//    An unexpected error occurred. please try again later
    CONST ERROR_WRONGLOGIN = '601';
    CONST ERROR_ALREADY_EXIST = '602';
    CONST ERROR_WRONG_DATA_TYPE = '603';
    CONST ERROR_EMPTY_FIELD = '604';
    const ERROR_NOTAVAILABLENOW = '605';
    const ERROR_ALREADY_UPLOADED = '607';
    const ERROR_VALID_INPUT = '999';
    const ERROR_EMAIL = '988';
    const ERROR_PASSWORD = '987';

}
